@localHost=localhost:4004/odata/v4/main

@headerId=32927063-cf11-4364-806f-7a5f8fa79b09
@customerId=86e82de8-82c9-425a-97e8-cb1372aa2eca
@productId=9e43df84-8ed7-4e40-ab8e-ea7c2e3056c2

GET http://{{localHost}}/SalesOrderHeaders?$filter=id eq {{headerId}} & $expand=items
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345

###

POST http://{{localHost}}/SalesOrderHeaders
Content-Type: application/json
Authorization: Basic cuka:Inicial@12345

{
    "id": "{{headerId}}",
    "customer_id": "{{customerId}}",
    "items": [
        {
            "id": "8f3b904d-54f4-4c21-981d-0db7da53b2de",
            "header_id": "{{headerId}}",
            "product_id": "{{productId}}",
            "quantity": 5,
            "price": 1.99
            
        },
        {
            "id": "36b6c68d-baa6-4e6b-9aa4-af787cdcbffd",
            "header_id": "{{headerId}}",
            "product_id": "{{productId}}",
            "quantity": 5,
            "price": 1.99
            
        }
      
    ]
}

###

DELETE  http://{{localHost}}/SalesOrderHeaders(id={{headerId}})
Content-Type: application/json

###

PUT http://{{localHost}}/SalesOrderHeaders(id=1234)
Content-Type: application/json
{
    "modifiedBy": "teste"
}

###

DELETE  http://{{localHost}}/SalesOrderHeaders(id=1234)
Content-Type: application/json


